default:
  # 服务监听端口
  listen: 8090
  log_dir: /Users/caoyuan/log
  # 日志级别，支持 INFO, WARN 和 ERROR, 默认为 INFO
  log_level: INFO
  # jwt 签名的 key
  jwt_key: gopixiu
  # 不启用kubeconfig文件检查
  is_kube_config: false

# 数据库地址信息
mysql:
  host: 42.192.54.11
  user: lbemi
  password: Admin_1234
  port: 3333
  name: gopixiu

cicd:
  driver: jenkins
  jenkins:
    host: http://8.140.165.201:9090
    user: adminops
    password: adminops@321
